src/CarPool/Models/Admin/MessageManage/PageDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarPool.Models.Admin.MessageManage
{
    public class PageDto
    {
        public PageDto()
        {
            QueryForm = new QueryConditionDto();
        }
        public QueryConditionDto QueryForm { get; set; }
    }
}

src/CarPool/Models/Admin/MessageManage/QueryConditionDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarPool.Models.Admin.MessageManage
{
    public class QueryConditionDto : BaseVModel
    {
        private string _startDate = DateTime.Now.ToString("yyyy-MM-dd");
        private string _endDate = DateTime.Now.ToString("yyyy-MM-dd");

        [Display(Name = "起点")]
        public string StartName { get; set; }
        [Display(Name = "出发开始日期")]
        public string StartTime { get { return _startDate; } set { _startDate = value; } }

        [Display(Name = "出发结束日期")]
        public string EndTime { get { return _endDate; } set { _endDate = value; } }

        [Display(Name = "消息类型")]
        public string MessageType { get; set; }
    }
}

src/CarPool/Controllers/MessageManageController.cs
using CarPool.Models.Admin.MessageManage;
using CarPool.Models.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarPool.Common;
using CarPool.Models;
using CarPool.Db.Entities;
using EntityFramework.Extensions;

namespace CarPool.Controllers
{
    [AllowAnonymous]
    public class MessageManageController : BaseController
    {
        public ActionResult Index()
        {
            return View(new PageDto());
        }
        
        public ContentResult Query(QueryConditionDto dto, Pager pager)
        {
            using (Db.CpDbContext db = new Db.CpDbContext())
            {
                DateTime startStartTime = Convert.ToDateTime(dto.StartTime);
                DateTime endStartTime = Convert.ToDateTime(dto.EndTime).AddDays(1);
                var dtos = new List<MessageVModel>();
                var query = db.Messages.AsNoTracking().AsQueryable();
                if (!string.IsNullOrEmpty(dto.StartName))
                    query = query.Where(t => t.StartName.Contains(dto.StartName));
                if(!string.IsNullOrEmpty(dto.MessageType))
                    query = query.Where(t => t.MessageType == (MessageType)Convert.ToInt32(dto.MessageType));
                query = query.Where(t => t.StartTime > startStartTime).Where(t => t.StartTime < endStartTime);
                query = query.Page(pager);
                query.ToList().ForEach(t => dtos.Add(t.ToVModel()));
                return ResultDataGrid<MessageVModel>(dtos, pager);
            }  
        }

        public ActionResult MessageEdit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return PartialView("_editForm", new MessageVModel());
            else
            {
                MessageVModel dto = new MessageVModel(); //_userService.GetUser(SafeConvert.ToInt64(id));
                return PartialView("_editForm", dto);
            }
        }
        
        public ContentResult Add(MessageVModel dto)
        {
            //_userService.AddUser(dto);
            return ResultSuccess<string>("添加成功");
        }
        
        public ContentResult Modify(MessageVModel dto)
        {
            //_userService.ModifyUser(dto);
            return ResultSuccess<string>("修改成功");
        }
        
        public ContentResult Remove(long? id)
        {
            //_userService.DeleteUser(new UserDto { Id = id });
            return ResultSuccess<string>("删除成功");
        }

        public ContentResult Top(string id)
        {
            using (Db.CpDbContext db = new Db.CpDbContext())
            {
                db.Messages.Where(t=>t.Id == id).Update(t=>new Message{ IsTop = true});
                db.SaveChanges();
            }
            return ResultSuccess<string>("顶置成功");
        }
    }
}

src/CarPool/Views/MessageManage/Index.cshtml
@using CarPool.Models.Admin.MessageManage
@model PageDto
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNormalFuncPage.cshtml";
}
@section head{
    <script type="text/javascript">
        var $lsGrid = {};
        $(document).ready(function () {
            $lsGrid = $("#grid").lsGrid({
                url: '@Url.Action("Query", "MessageManage")',
                title: "发布信息",
                fit: true,
                columns: [[
                    { title: '起点', field: 'StartName', width: 100, sortable: true, align: 'center' },
                    { title: '目的地', field: 'EndName', width: 100, sortable: true, align: 'center' },
                    {
                        title: '消息类型', field: 'MessageType', width: 80, sortable: true,align:'center', formatter: function (val) {
                            return val == 0 ? "车主" : "乘客";
                        }
                    },
                    {
                        title: '是否置顶', field: 'IsTop', width: 80, sortable: true, formatter: function (val) {
                            return val ? "是" : "否";
                        }, align: 'center'
                    },
                    { title: '出发时间', field: 'StartTime', width: 150, sortable: true, align: 'center' },
                    { title: '价格', field: 'Price', width: 50, sortable: true, align: 'center' },
                    { title: '人数/空座数', field: 'SeatCount', width: 50, sortable: true, align: 'center' },
                    { title: '联系电话', field: 'Phone', width: 150, sortable: true, align: 'center' ,align:'center'},
                    { title: '发布时间', field: 'PublishTime', width: 150, sortable: true, align: 'center' },
                    { title: '描述', field: 'Description', width: 350, sortable: true },

                ]]
            });
            page.init();
        });

        $.extend(page, {
            init: function () {
                $lsGrid.reload();
                $("#combo-msgType").lsCombobox({ data: [{ text: "车主", id: '0' }, { text: "乘客", id: '1' }] });
            },
            query: function () {
                $lsGrid.reload();
            },
            add: function () {
                $.ls.showDialog({
                    title: '新增用户',
                    url: '@Url.Action("UserEdit")',
                    width: 400,
                    height: 250,
                    onClose: function (result) {
                        if (result) {
                            $.ls.success($.ls.messages.SuccessAdded);
                            $lsGrid.reload();
                        }
                    }
                });
            },
            modify: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.showDialog({
                    title: '修改用户',
                    url: '@Url.Action("UserEdit")' + "?id=" + row.Id,
                    width: 400,
                    height: 250,
                    onClose: function (result) {
                        if (result) {
                            $.ls.success($.ls.messages.SuccessModified);
                            $lsGrid.reload();
                        }
                    }
                });
            },
            remove: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.confirm('确定删除?', function (result) {
                    if (result) {
                        $.ls.ajax({
                            url: '@Url.Action("Remove")' + '?id=' + row.Id,
                            onSuccess: function (data) {
                                $.ls.success($.ls.messages.SuccessDeleted);
                                $lsGrid.reload();
                            }
                        });
                    }
                })
            },
            top: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.confirm('确定置顶?', function (result) {
                    if (result) {
                        $.ls.ajax({
                            url: '@Url.Action("Top")' + '?id=' + row.Id,
                            onSuccess: function (data) {
                                $.ls.success($.ls.messages.SuccessOperation);
                                $lsGrid.reload();
                            }
                        });
                    }
                })
            }
        });
    </script>
}
@section btncontainer{
    <button onclick="page.query()" class="btn btn-primary">查询</button>
    <button onclick="page.top()" class="btn btn-primary">置顶</button>
}
@section queryform{
    @Html.Partial("_queryForm", Model.QueryForm)
}
<table id="grid"></table>

src/CarPool/Views/MessageManage/_queryForm.cshtml
@using CarPool.Models.Admin.MessageManage
@model QueryConditionDto
<table>
    <tr>
        <td>@Html.LabelFor(t => t.StartName)</td>
        <td>@Html.TextBoxFor(t => t.StartName, new { @class = "easyui-textbox", @placeholder = "起点" })</td>
        <td>@Html.LabelFor(t => t.StartTime)</td>
        <td>@Html.TextBoxFor(t => t.StartTime, new { @class = "easyui-datebox", @placeholder = "出发开始时间" })</td>
        <td>@Html.LabelFor(t => t.EndTime)</td>
        <td>@Html.TextBoxFor(t => t.EndTime, new { @class = "easyui-datebox", @placeholder = "出发结束时间" })</td>
        <td>@Html.LabelFor(t => t.MessageType)</td>
        <td>@Html.TextBoxFor(t => t.MessageType, new { @class = "easyui-combobox", @placeholder = "出发结束时间",@id= "combo-msgType" })</td>
    </tr>
</table>