src/CarPool/Models/Admin/AdvertManage/AdvertDto.cs
using System.ComponentModel.DataAnnotations;

namespace CarPool.Models.Admin.AdvertManage
{
    public class AdvertDto : BaseVModel
    {
        public AdvertDto()
        {
            
        }
        [Display(Name = "标题")]
        [Required(ErrorMessage = "请输入标题")]
        public string Title { get; set; }
        
        [Display(Name = "图片")]
        [Required(ErrorMessage = "请上传图片")]
        public string ImageUrl { get; set; }
        
        [Display(Name = "描述")]
        public string Description { get; set; }
    }
}

src/CarPool/Models/Admin/AdvertManage/PageDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarPool.Models.Admin.AdvertManage
{
    public class PageDto
    {
        public PageDto()
        {
            QueryForm = new QueryConditionDto();
        }
        public QueryConditionDto QueryForm { get; set; }
    }
}

src/CarPool/Models/Admin/AdvertManage/QueryConditionDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarPool.Models.Admin.AdvertManage
{
    public class QueryConditionDto : BaseVModel
    {
        [Display(Name = "标题")]
        public string Title { get; set; }
    }
}

src/CarPool/Controllers/AdvertManageController.cs
using CarPool.Models.Admin.AdvertManage;
using CarPool.Models.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarPool.Common;
using EntityFramework.Extensions;
using CarPool.Db.Entities;
using System.IO;

namespace CarPool.Controllers
{
    [AllowAnonymous]
    public class AdvertManageController : BaseController
    {
        const string FILE_PATH = "~/FileUpLoad/Adverts/";
        public ActionResult Index()
        {
            return View(new PageDto());
        }
        
        public ContentResult Query(QueryConditionDto dto, Pager pager)
        {
            using (Db.CpDbContext db = new Db.CpDbContext())
            {
                var dtos = new List<AdvertDto>();
                var query = db.Adverts.AsNoTracking().AsQueryable();
                if (!string.IsNullOrEmpty(dto.Title))
                    query = query.Where(t => t.Title.Contains(dto.Title));
                query = query.Page(pager);
                query.ToList().ForEach(t=>dtos.Add(new AdvertDto
                {
                    Title = t.Title,
                    ImageUrl = t.ImageUrl.Trim('~'),
                    Description = t.Description,
                    Id = t.Id
                }));
                return ResultDataGrid<AdvertDto>(dtos, pager);
            }  
        }

        public ActionResult AdvertEdit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return PartialView("_editForm", new AdvertDto());
            else
            {
                AdvertDto dto = new AdvertDto(); //_AdvertService.GetAdvert(SafeConvert.ToInt64(id));
                return PartialView("_editForm", dto);
            }
        }
        
        public ContentResult Add(AdvertDto dto)
        {
            using (Db.CpDbContext db = new Db.CpDbContext())
            {
                dto.ImageUrl = SaveFile();
                if (string.IsNullOrEmpty(dto.ImageUrl)) throw new ApplicationException("文件上传失败！");
                Advert advert = new Db.Entities.Advert
                {
                    Id = Guid.NewGuid().ToString(),
                    Title = dto.Title,
                    ImageUrl = dto.ImageUrl,
                    Description = dto.Description
                };
                db.Adverts.Add(advert);
                db.SaveChanges();
            }
            return ResultSuccess<string>("添加成功");

        }

        private string SaveFile()
        {
            string info = string.Empty;
            try
            {
                //获取客户端上传的文件集合
                HttpFileCollection files = System.Web.HttpContext.Current.Request.Files;
                //判断是否存在文件
                if (files.Count > 0)
                {
                    //获取文件集合中的第一个文件(每次只上传一个文件)
                    HttpPostedFile file = files[0];
                    //定义文件存放的目标路径
                    string targetDir = System.Web.HttpContext.Current.Server.MapPath(FILE_PATH);
                    //创建目标路径
                    Directory.CreateDirectory(targetDir);
                    //组合成文件的完整路径
                    string path = System.IO.Path.Combine(targetDir, System.IO.Path.GetFileName(file.FileName));
                    //保存上传的文件到指定路径中
                    file.SaveAs(path);
                    info =FILE_PATH + file.FileName;
                }
                else 
                    throw new ApplicationException("请选择文件");
            }
            catch
            {
                info = "";
            }
            return info;
        }

        public ContentResult Modify(AdvertDto dto)
        {
            
            return ResultSuccess<string>("修改成功");
        }
        
        public ContentResult Remove(string id)
        {
            using (Db.CpDbContext db = new Db.CpDbContext())
            {
                db.Adverts.Where(t => t.Id == id).Delete();
                db.SaveChanges();
            }
            return ResultSuccess<string>("删除成功");
        }
    }
}

src/CarPool/Views/AdvertManage/Index.cshtml
@using CarPool.Models.Admin.AdvertManage
@model PageDto
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNormalFuncPage.cshtml";
}
@section head{
    <script type="text/javascript">
        var $lsGrid = {};
        $(document).ready(function () {
            $lsGrid = $("#grid").lsGrid({
                url: '@Url.Action("Query", "AdvertManage")',
                title: "广告信息",
                fit: true,
                columns: [[
                    { title: '标题', field: 'Title', width: 150, sortable: true },
                    {
                        title: '图片', field: 'ImageUrl', width: 150, formatter: function (val) {
                            return '<img height="100" src=' + val + ' />'
                        }
                    },
                    { title: '描述', field: 'Description', width: 150, sortable: true }
                ]]
            });
            page.init();
        });

        $.extend(page, {
            init: function () {
                $lsGrid.reload();
            },
            query: function () {
                $lsGrid.reload();
            },
            add: function () {
                $.ls.showDialog({
                    title: '新增广告',
                    url: '@Url.Action("AdvertEdit")',
                    width: 400,
                    height: 250,
                    onClose: function (result) {
                        if (result) {
                            $.ls.success($.ls.messages.SuccessAdded);
                            $lsGrid.reload();
                        }
                    }
                });
            },
            modify: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.showDialog({
                    title: '修改广告',
                    url: '@Url.Action("AdvertEdit")' + "?id=" + row.Id,
                    width: 400,
                    height: 250,
                    onClose: function (result) {
                        if (result) {
                            $.ls.success($.ls.messages.SuccessModified);
                            $lsGrid.reload();
                        }
                    }
                });
            },
            remove: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.confirm('确定删除?', function (result) {
                    if (result) {
                        $.ls.ajax({
                            url: '@Url.Action("Remove")' + '?id=' + row.Id,
                            onSuccess: function (data) {
                                $.ls.success($.ls.messages.SuccessDeleted);
                                $lsGrid.reload();
                            }
                        });
                    }
                })
            }
        });
    </script>
}
@section btncontainer{
    <button onclick="page.query()" class="btn btn-primary">查询</button>
    <button onclick="page.add()" class="btn btn-primary">新增</button>
    <button onclick="page.modify()" class="btn btn-primary">修改</button>
    <button onclick="page.remove()" class="btn btn-primary">删除</button>
}
@section queryform{
    @Html.Partial("_queryForm", Model.QueryForm)
}
<table id="grid"></table>

src/CarPool/Views/AdvertManage/_editForm.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDialogPage.cshtml";
}
@using CarPool.Models.Admin.AdvertManage
@model AdvertDto
@section script{
    <script type="text/javascript">
        var dialog = top.dialog.get(window);
        var dialogObj = {
            Ok: function () {
                //获取form数据
                var formData = new FormData($("#formEdit")[0]);
                //调用apicontroller后台action方法，将form数据传递给后台处理。contentType必须设置为false,否则chrome和firefox不兼容
                $.ls.ajax({
                    url: '@Url.Action("Add")',
                    type: 'POST',
                    data: formData,
                    async: false,
                    cache: false,
                    contentType: false,
                    processData: false,
                    onSuccess: function (data) {
                        dialog.Close(true);
                    }
                });
                
            },
            Cancel: function () {
                dialog.Close(false); 
            }
        };

        $(document).ready(function () {
            $("#file").filebox({
                buttonText: '选择文件',
                buttonAlign: 'right'
            })
        });
    </script>
}
<div class="container">
    <form id="formEdit" class="form-horizontal">
        @Html.HiddenFor(x => x.Id,new {@id = "hidId"})
        <table>
            <tr>
                <td>@Html.LabelFor(x => x.Title)</td>
                <td>@Html.TextBoxFor(x => x.Title, new { @class = "easyui-textbox" })</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(x => x.ImageUrl)</td>
                <td>@Html.TextBoxFor(x => x.ImageUrl, new { @class = "easyui-filebox" ,@id="file"})</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(x => x.Description)</td>
                <td>@Html.TextAreaFor(x => x.Description, new { @class = "textarea" })</td>
            </tr>
        </table>
    </form>
</div>
@section buttons{
    <button class="btn btn-primary" onclick="dialogObj.Ok()">确认</button>
    <button class="btn btn-primary" onclick="dialogObj.Cancel()">取消</button>
}

src/CarPool/Views/AdvertManage/_queryForm.cshtml
@using CarPool.Models.Admin.AdvertManage
@model QueryConditionDto
<table>
    <tr>
        <td>@Html.LabelFor(t => t.Title)</td>
        <td>@Html.TextBoxFor(t => t.Title, new { @class = "easyui-textbox", @placeholder = "标题" })</td>
        <td></td>
        <td></td>
    </tr>
</table>