src/CarPool/Models/Admin/UserManage/PageDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarPool.Models.Admin.UserManage
{
    public class PageDto
    {
        public PageDto()
        {
            QueryForm = new QueryConditionDto();
        }
        public QueryConditionDto QueryForm { get; set; }
    }
}

src/CarPool/Models/Admin/UserManage/QueryConditionDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarPool.Models.Admin.UserManage
{
    public class QueryConditionDto : BaseVModel
    {
        [Display(Name = "用户名")]
        public string UserName { get; set; }
    }
}

src/CarPool/Models/Admin/UserManage/UserDto.cs
using System.ComponentModel.DataAnnotations;

namespace CarPool.Models.Admin.UserManage
{
    public class UserDto : BaseVModel
    {
        public UserDto()
        {
            
        }
        /// <summary>
        /// 用户名
        /// </summary>
        [Display(Name = "用户名")]
        [Required(ErrorMessage = "请输入用户名")]
        public string UserName { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        [Display(Name = "性别")]
        public string Sex { get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
        [Display(Name = "联系电话")]
        public string Phone { get; set; }
    }
}

src/CarPool/Controllers/UserManageController.cs
using CarPool.Models.Admin.UserManage;
using CarPool.Models.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarPool.Common;

namespace CarPool.Controllers
{
    [AllowAnonymous]
    public class UserManageController : BaseController
    {
        public ActionResult Index()
        {
            return View(new PageDto());
        }
        
        public ContentResult Query(QueryConditionDto dto, Pager pager)
        {
            using (Db.CpDbContext db = new Db.CpDbContext())
            {
                var dtos = new List<UserDto>();
                var query = db.Users.AsNoTracking().AsQueryable();
                if (!string.IsNullOrEmpty(dto.UserName))
                    query = query.Where(t => t.Name.Contains(dto.UserName));
                query = query.Page(pager);
                query.ToList().ForEach(t=>dtos.Add(new UserDto {
                    UserName = t.Name,
                    Sex = t.Sex,
                    Phone = t.Phone,
                    Id = t.Id
                }));
                return ResultDataGrid<UserDto>(dtos, pager);
            }  
        }

        public ActionResult UserEdit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return PartialView("_editForm", new UserDto());
            else
            {
                UserDto dto = new UserDto(); //_userService.GetUser(SafeConvert.ToInt64(id));
                return PartialView("_editForm", dto);
            }
        }
        
        public ContentResult Add(UserDto dto)
        {
            //_userService.AddUser(dto);
            return ResultSuccess<string>("添加成功");
        }
        
        public ContentResult Modify(UserDto dto)
        {
            //_userService.ModifyUser(dto);
            return ResultSuccess<string>("修改成功");
        }
        
        public ContentResult Remove(long? id)
        {
            //_userService.DeleteUser(new UserDto { Id = id });
            return ResultSuccess<string>("删除成功");
        }
    }
}

src/CarPool/Views/UserManage/Index.cshtml
@using CarPool.Models.Admin.UserManage
@model PageDto
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNormalFuncPage.cshtml";
}
@section head{
    <script type="text/javascript">
        var $lsGrid = {};
        $(document).ready(function () {
            $lsGrid = $("#grid").lsGrid({
                url: '@Url.Action("Query", "UserManage")',
                title: "用户信息",
                fit: true,
                columns: [[
                    { title: '用户名', field: 'UserName', width: 150, sortable: true },
                    { title: '性别', field: 'Sex ', width: 100 },
                    { title: '联系电话', field: 'Phone', width: 150, sortable: true }
                ]]
            });
            page.init();
        });

        $.extend(page, {
            init: function () {
                $lsGrid.reload();
                $("#combo-role").lsCombobox({ data: page.JsonData.Roles });
            },
            query: function () {
                $lsGrid.reload();
            },
            add: function () {
                $.ls.showDialog({
                    title: '新增用户',
                    url: '@Url.Action("UserEdit")',
                    width: 400,
                    height: 250,
                    onClose: function (result) {
                        if (result) {
                            $.ls.success($.ls.messages.SuccessAdded);
                            $lsGrid.reload();
                        }
                    }
                });
            },
            modify: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.showDialog({
                    title: '修改用户',
                    url: '@Url.Action("UserEdit")' + "?id=" + row.Id,
                    width: 400,
                    height: 250,
                    onClose: function (result) {
                        if (result) {
                            $.ls.success($.ls.messages.SuccessModified);
                            $lsGrid.reload();
                        }
                    }
                });
            },
            remove: function () {
                var row = $lsGrid.getSelectedRow();
                if ($.ls.isNullOrEmpty(row)) return;
                $.ls.confirm('确定删除?', function (result) {
                    if (result) {
                        $.ls.ajax({
                            url: '@Url.Action("Remove")' + '?id=' + row.Id,
                            onSuccess: function (data) {
                                $.ls.success($.ls.messages.SuccessDeleted);
                                $lsGrid.reload();
                            }
                        });
                    }
                })
            }
        });
    </script>
}
@section btncontainer{
    <button onclick="page.query()" class="btn btn-primary">查询</button>
}
@section queryform{
    @Html.Partial("_queryForm", Model.QueryForm)
}
<table id="grid"></table>

src/CarPool/Views/UserManage/_queryForm.cshtml
@using CarPool.Models.Admin.UserManage
@model QueryConditionDto
<table>
    <tr>
        <td>@Html.LabelFor(t => t.UserName)</td>
        <td>@Html.TextBoxFor(t => t.UserName, new { @class = "easyui-textbox", @placeholder = "用户名" })</td>
        <td></td>
        <td></td>
    </tr>
</table>